New cli command modify-user CLI & more jsdoc & small improvements
saltcorn/saltcorn pull request #1201
Opened 2022-05-24 21:17 UTC by AleksandrSokolov

2022-05-24 21:24 UTC, AleksandrSokolov commented
Also make some improvements in install  script (npx saltcorn-install). 
Adds:

- -e, --expert Expert mode, more abilities for configuration (Not compatible with -y)
- -d, --dryrun Dry Run mode, displays the operations that would be performed using the specified command without actually running them

2022-05-25 15:35 UTC, glutamate requested changes
thank you for fixing many bugs here. see the comments, only small changes

2022-05-25 15:35 UTC, glutamate commented on packages/saltcorn-cli/src/commands/create-user.js
> +const { loadAllPlugins } = require("@saltcorn/server/load_plugins");
Imports that import the database module (or does so transitively e.g. server) and therefore initialise the database connection should be done inside the methods. I can't remember exactly what it is that goes wrong if you don't do this but one of the commands requires this. having the imports outside the class declaration in just one cli command means that the database will be connected in all of the commands before running. 

This is also why the functions in common do their imports inside the functions.

However you can make this much shorter by using init_some_tenants. this was only recently introduced and has not been implemented in all the commands but have a look at configuration-check as an example

2022-05-25 15:35 UTC, glutamate commented on packages/saltcorn-cli/src/commands/modify-user.js
> +const {loadAllPlugins} = require("@saltcorn/server/load_plugins");
see comment on create-user; move imports inside methods

2022-05-26 07:11 UTC, AleksandrSokolov commented on packages/saltcorn-cli/src/commands/modify-user.js
> +const {loadAllPlugins} = require("@saltcorn/server/load_plugins");
Updated  according review

2022-05-26 07:30 UTC, AleksandrSokolov commented
Update according @glutamate review. Fix package.json

2022-05-26 08:54 UTC, glutamate requested changes
one change - delete import

2022-05-26 08:54 UTC, glutamate commented on packages/saltcorn-cli/src/commands/modify-user.js
> +const User = require("@saltcorn/data/models/user");
i think you forgot to delete this line (needs to be inside, which it is)

2022-05-26 11:02 UTC, glutamate approved these changes

2022-05-26 11:11 UTC, merged