Add new CLI commands, more internationalization, small fixes
saltcorn/saltcorn pull request #1961
Opened 2023-08-21 00:34 UTC by AleksandrSokolov

1. New CLI commands.
2. Improved Internationalization.
3. Updated Russian translation.
4. Small bug fixes

2023-08-22 08:19 UTC, pyhedgehog requested changes

2023-08-22 08:19 UTC, pyhedgehog commented on packages/saltcorn-data/base-plugin/viewtemplates/viewable_fields.js
> +            : __(column.action_label) || __(column.action_name);
What if translation not exists?

2023-08-24 23:39 UTC, AleksandrSokolov commented
@pyhedgehog I made update accroding your comments with some adtional improvements. Please see.

2023-08-25 19:10 UTC, pyhedgehog commented
> @pyhedgehog I made update accroding your comments with some adtional improvements. Please see.

1. You've forgot to revert help change in `packages/saltcorn-cli/src/commands/install-pack.js`.
2. I've checked on sqlite3 (i.e. non-multitenant) installation and `run-trigger` works.
3. I've checked `run-sql` and it works.

2023-08-26 12:34 UTC, angemarius939 commented
Generate JavaScript function code for this case: 


If I select one district among: Gakenke, Rulindo, Nyarugenge district in another variable bring only corresponding sectors to district selected: sectors for Gakenke: Rushashi, Muyongwe,Minazi. The sectors for Rulindo district are: Tare, Shyorongi, Kinihira. The sectors for Nyarugenge District are: Rugarama, Muhima, Kigali.

2023-08-26 12:34 UTC, angemarius939 commented
Generate JavaScript function code for this case: 


If I select one district among: Gakenke, Rulindo, Nyarugenge district in another variable bring only corresponding sectors to district selected: sectors for Gakenke: Rushashi, Muyongwe,Minazi. The sectors for Rulindo district are: Tare, Shyorongi, Kinihira. The sectors for Nyarugenge District are: Rugarama, Muhima, Kigali.

2023-08-29 06:32 UTC, AleksandrSokolov commented
@glutamate Please review and help with CI

2023-08-31 08:33 UTC, glutamate commented
@AleksandrSokolov Thanks for this. I have been away - will look later today

2023-08-31 15:42 UTC, glutamate commented
Thanks, this is very useful, especially run-sql will save a lot of time. Somethings may be improved by switching to console.table for outputting lists of things, but I think this is a general comment for a lot of the CLI cmds so we can do that later

2023-08-31 15:42 UTC, merged